uxshop/design-system

src/components/admin/codemirror/Codemirror.vue

- O componente `Codemirror` não estava alterando o valor do model ao editar, agora está

[Fix] Correção no codemirror

---

src/components/ui/form-autocomplete/FormAutocomplete.scss
src/components/ui/form-autocomplete/FormAutocomplete.vue

[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=1378)
- Ajuste visual

[Fix] Produtos Kit / Remover Press to Select da listagem de grupos de componentes

---

src/components/admin/browser-select/BrowserSelect.scss
src/components/admin/browser-select/BrowserSelect.vue
src/components/ui/form-autocomplete/FormAutocomplete.vue
src/components/ui/form-select/FormSelect.vue

- Adicionadas props opcionais no componente`BrowserSelect`:
- `hideExcludeButton` quando `true` não exibe o botão de excluir o registro da lista
- `searchDisabled` quando `true` desabilita o botão "pesquisar" e o input de busca  
- Adicionado espaçamento entre a lista e o input de pesquisa
- Adicionada prop disabled no componente `FormSelect`

[Task] Adicionar props de disabled

---

src/components/admin/page-helper-video/PageHelperVideo.vue
src/components/admin/page-helper-video/PageHelperVideoModal.vue
src/components/admin/page/Page.vue
src/components/ui/youtube-player/YoutubePlayer.vue

[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2013?workitem=6754)
- Remoção do ícone da base de conhecimento no componente `PageHelperVideoModal`
- Adição das props `title` e `supportTitle` com textos default caso elas não forem passadas na utilização do componente

[Hotfix] Remoção do ícone da base de conhecimento

---

src/components/admin/page-helper-video/PageHelperVideo.vue
src/components/admin/page-helper-video/PageHelperVideoModal.vue

- Substituição da validação de nome do video por video_id
- Remoção da validação por video_id no modal do PageHelperVideo
obs: Essas alterações estão agora de volta ao seu estado original.

[Fix] Remover alterações de validação do PageHelperVideo 

---

src/components/admin/browser-select/BrowserSelect.vue

- Adicionada chamada da função `first` vinda da prop service para o funcionamento do componente quando a prop `select-one` for `true`

[Hotfix] Correção no componente BrowserSelect

---

src/components/ui/modal/Modal.vue

- Remoção do evento de esc keydown diretamente na div, esse evento conflitava com o addEventListener de keydown que disparava outra função para fechar o modal.

[Hotfix] Remover evento "duplicado" de keydown esc

---

src/components/admin/table-list/table-list-nav-bulk/TableListNavBulk.vue
src/types/ITableListConfig.ts

- Adição da prop opcional `dialogDelete` de configuração no componente `TableList`, com ela é possível customizar os atributos de título, texto, label/ícone do botão da deleção de registros no TableList.

[Hotfix] Adicionar mensagem customizada no modal de Delete do TableList

---

src/components/ui/form-autocomplete/FormAutocomplete.vue

- Adição do parâmetro opcional `replaceOptions` para fazer a substituição do array de opções do `FormAutocomplete`.

[Task] Adicionar parâmetro para substituir todas options no select

---

src/components/ui/dropdown/Dropdown.vue

[Bug](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2020?workitem=8708)
- Adiciona evento `focusout` com função hide no dropdown

[Hotfix] Dropdown não fecha

---

src/components/ui/dropdown/Dropdown.vue

- Adicionado o operador optional chaining no event do listener do click fora do dropdown.

[Hotfix] Itens dentro do dropdown não tem a função de click executada.

---

src/components/ui/form-datepicker/FormDatepicker.vue

Changes:
- A prop config do FormDatepicker passada como options para o easepick, dando a possibilidade de passar opções de forma livre para o plugin.

[Hotfix] Prop de Config passando para o plugin easepick em FormDatepicker

---

src/components/admin/page-helper-articles/PageHelperArticles.stories.js
src/components/admin/page-helper-articles/PageHelperArticles.vue
src/components/admin/page-helper-articles/PageHelperArticlesModal.vue
src/components/admin/page-helper-video/PageHelperVideo.vue
src/components/admin/page-helper-video/PageHelperVideoModal.vue
src/components/admin/page-helper/PageHelper.scss
src/components/admin/page-helper/PageHelper.stories.js
src/components/admin/page-helper/PageHelper.vue
src/components/admin/page/Page.vue
src/components/admin/titlebar/Titlebar.vue

- Cria componente `PageHelperArticles`
- Atualiza componente `Page` adicionando logica para renderizar `PageHelperArticles` quando `video_id` não for passado porem existe uma lista de `articles`
- Cria escopo para diretiva `v-if` no componente `TitleBar`
- Atualiza tipagem `IVideo`
- Adapta componente `PageHelper` de modo a ser possível utiliza-lo como parte do `PageHelperArticles`

[Hotfix] Atualiza comportamento dos links no componente Page

---

src/components/ui/badge/Badge.vue

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11110)
- adicionado slot ao componente para permitir uso de conteudo sem a prop label explicita

[fix] table-list-item não mostra o badge

---

src/components/ui/divider/Divider.scss

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11042)
- corrigido cor do componente no dark mode

[fix] ui-divider está sem configs de dark mode

---

src/components/admin/user-profile-card/partials/UserButton.scss

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11791)
- adicionado elipse ao caption (nome da loja) da sidebar
- acionado tamanho maximo

[fix] nome da loja em overflow em elipse em "minha conta"

---

src/components/admin/sidebar/Sidebar.scss

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11901)
- corrigido tamanho da sidebar (isso fazia com que o position e o translate não ficassem precisos)

[fix] ao scrollar a tela o card de usuário fica aparecendo no mobile

---

src/components/admin/user-profile-card/partials/UserButton.scss

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/12004)
- corrigido radius da imagem da sidebar
- removido padding entre a borda e a imagem

[fix] border-radius na imagem do avatar

---

src/components/ui/modal/Modal.vue

- Remoção da `ref` desnecessária removendo a reatividade da prop.

[Fix] Reatividade do title do componente Modal 

---

src/components/admin/titlebar/Titlebar.scss
src/components/ui/badge/Badge.scss
src/components/ui/badge/Badge.vue
src/components/ui/card/Card.scss
src/components/ui/form-layout/FormLayoutItem.vue
src/components/ui/grid/col/Col.scss

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/12638)
- ajustado paddings de `Col`
- adicionado prop `noWrap` para `Badge`
- corrigido agrupamento dos campos no mobile
- removido margin negativa em link dentro de `Card`
- adicionado ellipsis no desktop para o nome do produto em seu detalhe

[fix] ajustes visuais do painel de controle

---

src/components/admin/browser-select/BrowserSelectModal.vue

- Adição da validação para adicionar a função `zerofill` somente para números menores que 10 no `BrowserSelectModal`.

[Fix] Validação para o fill de 0 somente abaixo de 10

---

package.json
src/components/admin/page-helper-video/PageHelperVideo.vue
src/components/admin/page-helper-video/PageHelperVideoModal.vue
src/components/admin/page-helper-video/index.ts
src/components/admin/page-helper-video/types.ts
src/components/admin/page/Page.vue
src/index.ts

Visando facilitar o reuso de código dos tipos do DS no projeto do Hub Marketplace, separa os tipos do componente `PageHelperVideo` em outro arquivo e o exporta junto com o componente na biblioteca, permitindo o uso.

Separa os tipos do componente PageHelperVideo em outro arquivo
