src/components/admin/page-helper/PageHelper.scss
- Removido background-color no pagehelper
=> fix: removido background-color no pagehelper

src/components/admin/userbar/Userbar.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=979)
- Adição da opção de link externo no dropdown do Userbar
=> [Fix] Menu / Contrate um especialista sem link

src/components/ui/form-currency/FormCurrency.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=986)
- Valor máximo em FormCurrency
=> [Fix] Grupo de Clientes / Compra mínima

src/components/admin/userbar/Userbar.vue, src/components/ui/dropdown/DropdownItem.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=991)
- Possibilidade de abrir links do drobdown do userbar em nova guia
=> [Fix] Links em nova guia no dropdow do userbar

src/components/admin/userbar/Userbar.scss
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=1030)
- Tamanho padrão na imagem de usuário na userbar
=> [Fix] Usuário / Foto fora do tamanho padrão

src/components/admin/page-helper/PageHelper.vue, src/components/admin/page/Page.vue, src/components/admin/titlebar/Titlebar.vue
- link adicionado ao TitleBar
- link PageHelperVideo em target="_blank"
=> task: botao-editar-templates-de-e-mail

src/components/ui/form-tags/FormTags.vue
- Possibilidade de iniciar com valor, caso for select
- Emite evento de remoção
=> [Feat] Iniciar com valor, e evento de remoção

src/components/ui/form-currency/FormCurrency.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=1152)
- Altera o reg apenas se o novo valor não for null no watch
=> [Fix] Produtos / Erro ao descartar alterações

src/components/ui/form-autocomplete/FormAutocomplete.vue, src/components/ui/form-tags/FormTags.vue
=> [Fix] Instância choices

src/components/admin/table-list/table-list-nav/TableListNavCustomFilter.vue, src/components/admin/table-list/table-list-tabs/TableListTabs.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=1383)
- Edição de filtro sem ter que atualizar a página
=> [Fix] Opção de editar filtro

src/components/admin/table-list/TableList.vue, src/components/admin/table-list/table-list-nav-bulk/TableListNavBulk.vue, src/components/admin/table-list/table-list-nav/TableListNavRefresh.vue, src/components/admin/table-list/types/ITableListState.ts, src/filters.ts
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%202?workitem=1382)
- Tratamento de erros ao excluir registro
=> [Fix] Cores / Não é possível apagar

src/components/ui/color-thumb/ColorThumb.scss, src/components/ui/color-thumb/ColorThumb.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1483)
- Imagens em ColorThumb
=> [Fix] Não é possível adicionar uma estampa na cor

src/components/ui/stack/Stack.scss
- Corrigino o align end do componente
=> [Fix] Stack align end

src/components/ui/aside/Aside.scss, src/components/ui/form-autocomplete/FormAutocomplete.vue, src/components/ui/form-tags/FormTags.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1447)
- Alteração na altura do Aside
=> [Fix] Responsividade / Aside

src/components/ui/icon/Icon.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1553)
- Remoção da classe `material-icons` que estava causando conflito nos 
- ícones
=> [Fix] Configurações / Ajuste visual

src/components/admin/table-list/TableList.vue
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1568)
- Adicionada a possibilidade de remover filtros no TableList
=> [Fix] Pedidos / Não é possível excluir os filtros selecionados

src/components/ui/form-richtext/FormRichtext.vue
[feat link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1586)
- Adicionada a prop de configCallbacks
=> [Feat] Adicionar upload de imagem no componente de richtext

src/components/admin/empty-data/EmptyData.scss
[fix link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1701)
- Alteração no tamanho do texto
=> [Fix] Mensagem com fonte maior que o padrão

src/components/admin/layout/Layout.scss, src/components/admin/table-list/table-list-nav/TableListNav.scss, src/types/ITableListConfig.ts
[feat link](https://dev.azure.com/doocacom/Painel/_sprints/taskboard/Painel%20Team/Painel/Sprint%203?workitem=1697)
- Position sticky no cabeçalho do `TableList`
=> [Feat] Position sticky no cabeçalho do TableList

src/components/admin/browser-select/BrowserSelect.vue, src/components/admin/browser-select/BrowserSelectModal.scss, src/components/admin/browser-select/BrowserSelectModal.vue, src/components/ui/aside/Aside.vue, src/components/ui/infinite-scroll/InfiniteScroll.vue
- Scroll infinito no browser select corrigido
=> [Fix] Scroll infinito no browser select

src/components/admin/media-card/MediaCard.scss, src/components/admin/media-card/MediaCard.vue
- Ajustes visuais no media card
=> [Fix] Visual media card

src/components/admin/table-list/table-list-nav/TableListNav.scss
[task link](https://dev.azure.com/doocacom/Platform/_boards/board/t/Suporte%20Team/Stories/?workitem=2424)
- Adicionada a largura mínima no input search
- Inserida rolagem automática no topo da tabela quando mobile.
=> fix: largura minima no imput search e rolagem na table nav

src/components/ui/timeline/Timeline.vue
[feat link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/Painel%20Team/Platform/Painel%201?workitem=2230)
- Adição e remoção da timeline
=> [Feat] Adição e remoção da timeline

src/components/admin/browser-select/BrowserSelectModal.vue
- Resetado os parâmetros de busca e array de rows a cada vez que a modal é aberta.
=> [Fix] Reset no BrowserSelectModal

src/components/ui/badge/Badge.scss
- Badge warning variation added on CSS
=> [Feat] Badge warning variation

src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.vue, src/components/admin/table-list/table-list-tags/TableListTags.vue, src/components/ui/form-datepicker/FormDatepicker.vue
[task link](https://dev.azure.com/doocacom/Platform/_boards/board/t/Suporte%20Team/Stories/?workitem=2935)
- Inserido o date picker nos filtros da tabela.
=> [Task] Relatórios de pedidos

src/components/admin/page/Page.vue, src/components/admin/row-exclude/RowExclude.vue, src/components/admin/savebar/Savebar.vue, src/components/ui/card/Card.scss, src/components/ui/card/Card.vue, src/components/ui/form-checkbox/FormCheckbox.scss, src/components/ui/form-radio/FormRadio.scss, src/scss/variables.scss
- Resetado os parâmetros de busca e array de rows a cada vez que a modal é aberta.
- Adicionado variação de warning no `Badge`
-  inclusão de filtro por período nas tabelas
- Adicionada validação de query params ao componente TableList
=> Release 1.2.0

src/components/ui/form-autocomplete/FormAutocomplete.vue
[task link](https://dev.azure.com/doocacom/Platform/_boards/board/t/squad-support/Stories/?workitem=2856)
- Aumentado o limite do input de busca.
=> [Task] Krause - Categorias nos produtos

src/components/admin/browser-select/BrowserSelect.vue, src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.vue, src/components/admin/table-list/table-list-tags/TableListTags.vue
[task link](https://dev.azure.com/doocacom/Platform/_boards/board/t/squad-support/Stories/?workitem=3076)
- Adicionada a opção de filtro por browser select e a tag de category_ids
=> fix: filtro de categoria com browser select

src/components/admin/table-list/TableList.vue
- Feita a validação da existência dos filtros no localStorage
=> [Fix] Validação localStorage

src/components/ui/button/Button.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5051)
- removido estilizações de classes descontinuadas
- feita a estilização com base nos tokens novos
=> [task] Refatorar os botões DS Dooca

src/components/ui/alert/Alert.scss, src/scss/colors.scss, src/scss/typography.scss
[feat link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5371)
- corrigido presets de tipografia
- corrigido cores do darkmode
- css do componente Alert refatorado, com uso dos novos tokens
=> [task] Refatorar CSS do componente Alert

src/components/ui/avatar/Avatar.scss, src/components/ui/avatar/Avatar.stories.js
[task link](xxxxxxxxxx)
- refatorado css do componente
- corrigido uso de prop no storybook
=> [task] Refatorar CSS do componente Avatar

src/components/ui/aside/Aside.scss, src/components/ui/aside/Aside.vue, src/scss/theme.scss
[task link](xxxxxxxxxx)
- css refatorad
- adicionado estilos de fonte padrão globalmente
=> [task] Refatorar CSS do componente Aside

src/components/ui/badge/Badge.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5377)
- css do componente badge refatorado
=> [task] Refatorar CSS do componente Badge

src/components/ui/breadcrumb/BreadCrumb.scss, src/components/ui/breadcrumb/BreadCrumbItem.scss, src/components/ui/breadcrumb/Breadcrumb.stories.js, src/components/ui/breadcrumb/UiBreadcrumb.vue, src/scss/table.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5378)
- Refatora css adicionando comportamento para telas mobile e deskTop
- Adiciona icone
[figma](https://www.figma.com/file/LzmW3VpvVbsj0vYEqc3JI1/Componentes---Dooca?node-id=27%3A645&t=fSoiYuAvwpuAktvr-0)
=> [Task] Refatora estilização Breadcrumb

src/components/ui/button/Button.scss, src/scss/spacing.scss
[fix link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5388)
- corrigido espaçamentos do botão
- alteradas as variáveis de espaçamento base
=> [fix] Ajustar espaçamento e fonte do botão

src/components/ui/alert/Alert.scss, src/components/ui/alert/Alert.stories.js, src/components/ui/aside/Aside.scss, src/components/ui/badge/Badge.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5519)
corrigido espaçamentos dos componentes:
- badge
- alert
=> [task] Ajustar espaçamento de componentes refatorados

src/components/ui/card/Card.scss, src/components/ui/card/Card.stories.js
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-6?workitem=5379)
- css refatorado
- footer e caption adicionado ao storybook
=> [task] Refatorar CSS do componente Card

src/components/admin/topbar/Topbar.vue
- Adição de slot para ações na navbar
=> [Feat] Adição de slot para ações na navbar

src/components/admin/media-card/MediaCard.scss, src/components/admin/media-card/MediaCard.stories.js, src/components/admin/media-card/MediaCard.vue, src/components/ui/button/Button.vue, src/types/IAction.ts
- Adicionada configuração para adicionar vários botões no componente Media Card.
=> [Feat] Botões no componente Media Card

src/components/ui/callout-card/CalloutCard.scss, src/components/ui/callout-card/CalloutCard.vue
- Adição de slot de append-to-header no CalloutCard
=> [Task] Slot de append-to-header no CalloutCard

src/components/admin/titlebar/Titlebar.vue, src/components/ui/dropdown/Dropdown.scss, src/components/ui/dropdown/DropdownItemButton.vue
- Adição de leading icon no dropdown
=> [Task] Leading icon no dropdown

src/components/admin/titlebar/Titlebar.vue, src/components/ui/dropdown/Dropdown.scss, src/components/ui/dropdown/DropdownItemButton.vue
- Adição de leading icon no dropdown
=> [Feat] Leading icon no dropdown

src/components/ui/callout-card/CalloutCard.scss, src/components/ui/callout-card/CalloutCard.vue
- Adição de slot de append-to-header no CalloutCard
=> [Feat] Slot de append-to-header no CalloutCard

src/components/admin/titlebar/Titlebar.vue
- Passada prop de `leading-icon` para o botão opcional de ação primária no título do componente TitleBar.
=> [Task] Adicionar ícone no botão do componente TitleBar

src/components/ui/aside/Aside.vue, src/components/ui/form-select/FormSelect.vue, src/components/ui/form-wrapper/FormWrapper.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-10?workitem=6242)
- corrigido estilização de inativo no campo de select
- adicionado possibilidade de usar o type reset nos botões
- adicionado opção default para o reset nos inputs de tipo selects
=> [task] Correção no aside de Contratos do Correio (Frete e Entrega)

src/components/admin/page/Page.vue, src/components/admin/titlebar/Titlebar.scss, src/components/admin/titlebar/Titlebar.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2011?workitem=6248)
- removidos códigos comentados
- alterado nomenclaturas
=> [task] Criação da tela do painel de lojista

src/components/admin/table-list/TableList.vue
- Adição do emit do evento `empty-data` quando a tabela não conter registros.
=> [Feat] Adicionado evento de empty-data

src/components/admin/page-helper-video/PageHelperVideo.vue, src/components/admin/page-helper-video/PageHelperVideoModal.vue
- altera o tipo de exibição caso seja passado o video_id
=> [Fix]: corrige exibição aside video

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue
- corrige permissões de rotas
- altera cor das categorias
=> [Task]altera links sidebar

src/components/admin/browser-select/BrowserSelect.vue
- Adicionada chamada da função `first` vinda da prop service para o funcionamento do componente quando a prop `select-one` for `true`
=> Release 2.1.2

src/components/admin/titlebar/Titlebar.scss, src/components/admin/titlebar/Titlebar.vue, src/types/IAction.ts
- Reposicionamento do subtitle no componente `Titlebar`
- Adição da propriedade `class` na interface `IAction`
=> [Hotfix] Reposicionamento do subtitle na titlebar

src/components/ui/form-currency/FormCurrency.vue, src/components/ui/form-textfield/FormTextfield.vue
- Corrigida a atualização do valor manipulado no componente FormCurrency removendo a validação de `focus` do input
=> [Hotfix] Correção da atualização do model no componente FormCurrency

src/components/ui/form-colorpicker/FormColorpicker.vue
- Adicionado v-bind nos atributos do input
=> [Hotfix] Adicionar placeholder no FormColorPicker

src/components/admin/table-list/TableList.vue
- Adicionada validação da equiparação dos objetos de filtro padrão do componente TableList com os filtros customizados (passados pelo usuário)
- O evento para identificar que a seção (ex: produtos/cores...) não tem nenhum registro só é emitido quando o retorno do get não tiver índices no array e quando usuário não utilizar nenhum filtro.
=> [Hotfix] Validação do emit de emptyData na TableList

src/components/admin/table-list/TableList.vue, src/components/ui/button/Button.scss, src/components/ui/form-colorpicker/FormColorpicker.vue, src/components/ui/form-currency/FormCurrency.vue, src/components/ui/form-textfield/FormTextfield.vue, src/components/ui/timeline/Timeline.vue
- Remoção do `z-index: 4;` do componente `Button`
- Remoção do componente `Avatar` do componente `Timeline`
- Correção da atualização do valor manipulado no componente `FormCurrency`, removendo a validação de focus do input
- Adição de validação da equiparação dos objetos de filtro padrão do componente `TableList` com os filtros customizados (passados pelo usuário). - Adição do Promises.all no delete dos itens do componente da `TableList`
- Adição do  emit `deletedItens` no componente `TableList`
- O evento para identificar que a seção (ex: produtos/cores...) que não tem nenhum registro só é emitido quando o retorno do get não tiver índices no array e quando usuário não utilizar nenhum filtro.
=> [Release] 2.1.4

src/components/admin/titlebar/Titlebar.vue, src/components/ui/aside/Aside.vue, src/components/ui/callout-card/CalloutCard.scss, src/components/ui/callout-card/CalloutCard.vue, src/components/ui/form-autocomplete/FormAutocomplete.vue
- Adição do parâmetro opcional `replaceOptions` para fazer a substituição do array de opções do `FormAutocomplete`.
- Remoção da variação de cor do botão no componente `Titlebar`.
- Adição das props de `justifyCardActions` e `bgColorIconPrimary` no componente `CalloutCard`.
=> Release 2.1.5

src/components/ui/dropdown/Dropdown.vue
- Correção do evento ao clicar fora do componente `Dropdown` para fechar o mesmo.
=> Release 2.1.6

src/components/ui/alert/Alert.vue, src/components/ui/button/Button.vue
- Correção da reatividade das propriedades de variação dos componentes `Alert` e `Button`
=> [Feature] Reatividade dos estilos de Alert e Button

src/components/admin/browser-select/BrowserSelectModal.vue
- Adição da prop `identifier` na chave que buscar o valor para marcar o checkbox
=> [Hotfix] Checkbox do BrowserSelectModal não funcionando

src/components/ui/form-richtext/FormRichtext.vue, src/components/ui/form-richtext/redactor/redactor.css
Task: Estender funcionalidades da area de texto de criação do blog
https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2026?workitem=9745
- Adiciona import do plugin
- Atualiza cor das tags H's e Quote da lib Redactor com o tema
=> [HotFix]: Adiciona import do plugin redactor alignment

src/components/ui/timeline/Timeline.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/9927)
- adicionado prop para ocultar botão de remoção de item
=> [task] criação da tela de ticket em andamento

src/components/ui/timeline/Timeline.vue
[us link](https://dev.azure.com/doocacom/Platform/_workitems/edit/9843)
- adicionado validação para exibir o botão de remover item
=> [us] usuário abre ticket de atendimento pelo painel de controle

src/scss/mixins/tokens.scss, src/scss/tokens/semantic/borders.scss, src/scss/tokens/semantic/spacing.scss, src/scss/tokens/tokens.scss
- corrigido nomenclaturas
- arquivos identados
=> [fix] corrigir nomenclatura de variaveis

src/types/IAction.ts, src/types/ITypes.ts, src/types/Types.ts
- adicionado tipos de size, variation, etc para melhor tipagem dos componentes
=> [task] adicionar novos tipos

src/components/admin/titlebar/Titlebar.vue, src/components/ui/button/Button.vue
[Task] Ajustar alinhamentos no ui-page
[Link Task](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2027?workitem=10045)
Changes:
- Componente Titlebar: Botões de ação responsivos, mostrando somente o ícone quando for mobile. Se o ícone não for informando, manter a label independente do tamanho da tela.
- Prop trailingIcon alterada dinamicamente pelo pai.
=> [Task] Ajustar alinhamentos no ui-page

src/components/ui/breadcrumb/BreadCrumb.scss, src/components/ui/breadcrumb/BreadCrumbItem.scss, src/components/ui/breadcrumb/Breadcrumb.stories.ts, src/components/ui/breadcrumb/BreadcrumbItem.vue
- Atualiza css
- Atualiza componente
- Cria novo story book
=> [task]: componente breadcrumb

src/components/ui/dialog/Dialog.scss, src/components/ui/dialog/Dialog.stories.ts, src/components/ui/dialog/Dialog.vue, src/components/ui/dialog/index.ts
- Refatora componente Dialog 
- Refatora css
- Cria stories
=> [Task] Refatora componente dialog

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue, src/components/admin/sidebar/types.ts, src/components/admin/user-profile-card/UserProfileCard.scss, src/components/admin/user-profile-card/UserProfileCard.vue, src/components/ui/news-indicator/NewsIndicator.scss, src/components/ui/news-indicator/NewsIndicator.vue, src/scss/animations/animation.scss, src/scss/animations/fade-in-out.scss, src/scss/animations/menu-animation.scss, src/scss/animations/move-horizontal.scss
**[Task] Animações de dropdown no menu**
[Task 9996](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2028?workitem=9996)
_Changes:_
- Inclusão das animações para uso na Sidebar
- Criação do componente de Indicador de Novidades para SideBar
=> [Task] Animações de dropdown no menu

src/components/admin/table-list/TableList.vue, src/components/admin/table-list/table-list-nav-filter/TableListNavFilter.vue
-  Adição da exposição da função `open` do componente `FilterSidebar` para expor também na `TableList`
=> [Feature] Adicionar expose da função de abertura de aside dos filtros da TableList

src/components/admin/table-list/table-list-nav/TableListNavCustomFilter.vue
- Remoção da adição duplicada das tabs ao salvar um filtro.
=> [Hotfix] Tab de filtro duplicada

src/components/ui/link/Link.vue
Adicionado o slot com fallback da label removendo o disabled fixo na tag.
=> [Fix] Correção do componente de slot

src/components/ui/form-checkbox/FormCheckbox.scss, src/components/ui/form-checkbox/FormCheckbox.stories.ts, src/components/ui/form-checkbox/FormCheckbox.vue
- Refatora componente `FormCheckbox`, css e cria stories
=> [Task] Refatora componente FormCheckbox

src/components/ui/list-group/ListGroup.scss, src/components/ui/list-group/ListGroup.stories.ts, src/components/ui/list-group/ListGroup.vue, src/components/ui/list-group/ListGroupItem.scss, src/components/ui/list-group/ListGroupItem.vue, src/components/ui/list-group/ListGroupItemButton.scss
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10102)
- adicionado documentaçao para o storybook
=> [task] refatorar componente list group

src/components/ui/description-list/DescriptionList.scss, src/components/ui/description-list/DescriptionList.stories.ts, src/components/ui/description-list/DescriptionList.vue, src/components/ui/description-list/components/description-list-item/DescriptionListItem.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10087)
- adicionado documentaçao para o storybook
=> [task] refatorar componente description list

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue
Adicionado `item.active` como parâmetro para exibição do dropdown.
=> [Fix] Correção do estado de active de um item quando dropdown

src/scss/tokens/semantic/typographies.scss, src/scss/tokens/stories/typography.stories.mdx
-  Adição do token semântico `s--typography-caption-large`
=> [Task] Criar token para caption large

src/components/admin/layout/Layout.scss, src/components/admin/sidebar/Sidebar.scss, src/components/ui/toast/Toast.scss, src/components/ui/toast/Toast.vue
###Changes:
- Correção dos valores de z-index.
=> [Fix] Correção do z-index na Sidebar e Toast

src/components/ui/tab/Tab.scss, src/components/ui/tab/Tab.stories.ts, src/components/ui/tab/TabItem.scss
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10110)
- adicionado documentaçao para o storybook
=> [task] refatorar componente tab

src/components/ui/stats-item/StatsItem.scss, src/components/ui/stats-item/StatsItem.stories.ts, src/components/ui/stats-item/StatsItem.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10109)
- adicionado documentaçao para o storybook
=> [task] refatorar componente stats-item

src/components/ui/infinite-scroll/InfiniteScroll.scss, src/components/ui/infinite-scroll/InfiniteScroll.stories.ts
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10100)
- adicionado documentação para o storybook
=> [task] refatorar componente infinite scroll

src/components/ui/timeline/Timeline.scss, src/components/ui/timeline/Timeline.stories.ts
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10113)
- adicionado documentação para o storybook
=> [task] refatorar componente timeline

src/components/ui/youtube-player/YoutubePlayer.stories.ts, src/components/ui/youtube-player/YoutubePlayer.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10115)
- adicionado documentação para o storybook
- refatorado componente
=> [task] refatorar componente youtube player

src/components/ui/tag/Tag.scss, src/components/ui/tag/Tag.stories.ts, src/components/ui/tag/Tag.vue, src/components/ui/tag/TagList.scss
[TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%201?workitem=11096)
- Adiciona slot
=> fix: ajusta slot tag

src/components/admin/table-list/table-list-nav/TableListNav.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11020)
- readicionado z-indexes às tableas
=> [fix] correções z-index

src/components/ui/alert/Alert.scss, src/components/ui/form-validation/FormValidation.stories.ts, src/components/ui/form-validation/FormValidation.vue
[TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%201?workitem=10891)
- Refatora componente, css e stories
=> [task] Refatora componente form validation

src/scss/tokens/tokens.scss
- ordenada a ordem de carregamento dos tokens, para que fiquem em ordem alfabetica
=> [task] ordenar alfabeticamente os tokens

src/components/admin/quick-search/QuickSearch.vue, src/components/admin/table-list/TableList.vue, src/components/ui/modal/Modal.vue
- Ajusta botão de close do modal
- Corrige handle de visibilidade do QuickSearch
- Modifica onMount da TableList adicionando o query param na request para carregar a listagem
=> [Fix] Busca rápida não funciona

src/components/admin/quick-search/QuickSearch.vue, src/constants/index.ts, src/helpers/index.ts
[TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11513)
- Adiciona botão de pesquisa no QuickSearch
=> [Task] adiciona botao de pesquisa no QuickSearch

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue, src/components/admin/user-profile-card/UserProfileCard.scss
[TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11525)
- Ajusta css
- Fixa footer sidebar
=> [Fix] Refatora sidebar

src/components/admin/table-list/table-list-nav/TableListNavSortable.vue, src/components/admin/table/Table.scss, src/components/admin/topbar/Topbar.vue, src/components/ui/aside/Aside.scss, src/components/ui/aside/Aside.vue, src/components/ui/dialog/Dialog.scss, src/components/ui/dialog/Dialog.vue, src/components/ui/dropdown/Dropdown.scss, src/components/ui/image/Image.vue
[TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11539)
[FIGMA](https://www.figma.com/file/zgZ2jtvgEFxIQ5HRM40Htk/Corre%C3%A7%C3%B5es-DS?type=design&node-id=77-462&mode=design&t=HJq7IMpNE2qsqGw5-0)
-  dialog 
-  aside  
-  dropdown
-  hover table
-  image
=> [Fix] Ajutes gerais nos componente ds

src/components/ui/form-textfield/FormTextfield.vue, src/components/ui/form-wrapper/FormWrapper.scss, src/scss/mixins.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11541)
- form textfield:
- - cores na variação de disabled
- form select
- - cor do icone de seleção
- - tamanho do icone de seleção
=> [fix] ajustes em select e text field

src/components/ui/button-group/ButtonGroup.scss, src/components/ui/card/Card.vue
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11540)
- card:
- - tamanho do ícone de dropdown
- button:
- - tamanho dos botões
=> [fix] ajustes em card e button group

src/components/ui/form-checkbox/FormCheckbox.scss, src/components/ui/form-radio/FormRadio.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11538)
- tamanhos corrigidos de:
- - form-checkbox
- - form-radio
=> [task] ajustar tamanho de radio button e checkbox

src/components/ui/modal/Modal.scss, src/components/ui/modal/Modal.vue
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11560)
- corrigido tamanho do icone de fechar
- corrigido cores e fonte dos titulos
=> [fix] correções no componente modal

src/components/ui/form-colorpicker/FormColorPicker.scss, src/components/ui/skeleton/Skeleton.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11562)
- corrigido cores no dark mode
=> [fix] corrigir cores dark mode de input color e skeleton

src/components/ui/card/Card.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11575)
- corrigido fonte da description do card
=> [fix] ajustar variável de texto no description do card

src/components/admin/sidebar/Sidebar.scss
- Customização de estilo da scrollbar do componente de Sidebar.
=> [Task] Customizar scroll da sidebar

src/components/ui/form-checkbox/FormCheckbox.scss, src/components/ui/form-radio/FormRadio.scss, src/components/ui/form-select/FormSelect.scss, src/components/ui/form-tags/FormTags.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11564)
- corrigido cor e fonte de `form-checkbox`e `form-radio`
- corrigido hover do `form-select`
- corrigido cor de fonte e borda ao focar de `form-tags`
=> [fix] token componente select, checkbox, radio e form tags

src/components/admin/sidebar/Sidebar.vue, src/components/admin/sidebar/types.ts, src/components/admin/user-profile-card/types.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11614)
- Fecha menus quando click em mobile
=> Task: handle mobile sidebar

src/components/admin/sidebar/Sidebar.scss, src/components/admin/user-profile-card/UserProfileCard.scss, src/components/admin/user-profile-card/partials/UserButton.scss, src/components/ui/modal/Modal.scss, src/components/ui/skeleton/Skeleton.scss
- Ajustes finos de espaçamento nos itens da sidebar.
- Correção do hover de close na modal.
- Correção na velocidade da animação.
=> [Task] Ajustes gerais layout

src/components/ui/dropdown/Dropdown.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11597)
- tokens e espaçamentos do componente corrigidos
=> [fix] dropdown errado no dark e no light mode

src/components/ui/tab/TabItem.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11648)
- tamanho da sidebar corrigido
=> [fix] ajustar cor do ui-tab-item-badge

src/components/admin/savebar/Savebar.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11619)
- token de tamanho da savebar corrigido
=> [fix] ajustar tamanho da savebar

src/components/admin/sidebar/types.ts, src/components/admin/table-list/TableList.scss, src/components/admin/table-list/TableList.vue, src/components/admin/table-list/snippets/TableListEmptyMessage.vue, src/components/admin/table-list/table-list-nav-bulk/TableListNavBulk.vue, src/components/admin/table-list/table-list-nav-filter/TableListNavFilter.vue, src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss, src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.vue, src/components/admin/table-list/table-list-nav-loader/TableListNavLoader.scss, src/components/admin/table-list/table-list-nav-loader/TableListNavLoader.vue, src/components/admin/table-list/table-list-nav-pagination/TableListNavPagination.scss, src/components/admin/table-list/table-list-nav-pagination/TableListNavPagination.vue, src/components/admin/table-list/table-list-nav/TableListNav.scss, src/components/admin/table-list/table-list-nav/TableListNavCustomFilter.vue, src/components/admin/table-list/table-list-nav/TableListNavRefresh.vue, src/components/admin/table-list/table-list-nav/TableListNavSearch.vue, src/components/admin/table-list/table-list-nav/TableListNavSortable.vue, src/components/admin/table-list/table-list-table/TableListTable.scss, src/components/admin/table-list/table-list-table/TableListTable.vue, src/components/admin/table-list/table-list-tabs/TableListTabs.scss, src/components/ui/form-richtext/FormRichtext.stories.ts, src/components/ui/icon-button/IconButton.scss, src/components/ui/icon-button/IconButton.vue, src/components/ui/tab/TabItem.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11626)
- Refatora css table list e realiza ajustes conforme nescessário
=> Task: Refatoração da table-list

src/components/ui/modal/Modal.vue
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11643)
- removido texto fixo no caption da modal
- adicionado prop de caption
=> [fix] ajustar modal

src/components/ui/tab/TabItem.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11629)
- corrigido cor no hover
=> [fix] ajustar component tab

src/components/admin/empty-data/EmptyData.scss, src/components/admin/empty-data/EmptyData.vue, src/components/admin/media-card/MediaCard.scss, src/components/admin/media-card/MediaCard.stories.ts, src/components/admin/stats/StatsGroup.scss, src/components/admin/stats/StatsGroup.stories.ts, src/components/admin/stats/StatsGroup.vue, src/components/admin/titlebar/Titlebar.scss, src/components/ui/card/Card.scss, src/components/ui/dropdown/Dropdown.scss, src/scss/helpers.scss
[Ajustar cor do divider](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11609)
[Corrigir componente de media card](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11616)
[Ajustar stats-group](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11634)
[seo wrapper](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11624)
=> Task: Refatora  MediaCard, EmptyData e StatsGroup components

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue, src/components/ui/news-indicator/NewsIndicator.vue
- Adição da prop `label` e componente `Badge` no componente `NewsIndicator`.
- Adição do `NewsIndicator` nos nodes dos itens da `Sidebar`.
=> [Fix] Não exibe tag de menu novo

src/components/admin/sidebar/Sidebar.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11727)
- remove close menu no click em mobile
=> Fix: Fechando o menu ao selecionar opção no mobile

src/components/admin/empty-data/EmptyData.scss, src/components/admin/page-helper-video/PageHelperVideo.scss, src/components/admin/page-helper/PageHelper.scss, src/components/admin/page/Page.scss, src/components/admin/page/Page.vue, src/components/admin/savebar/Savebar.scss, src/components/admin/sidebar/Sidebar.scss, src/components/admin/table-list/TableList.scss, src/components/admin/table-list/table-list-nav-bulk/TableListNavBulk.vue, src/components/admin/table-list/table-list-nav-pagination/TableListNavPagination.vue, src/components/admin/table-list/table-list-nav/TableListNav.scss, src/components/admin/table-list/table-list-nav/TableListNavCustomFilter.vue, src/components/admin/table-list/table-list-nav/TableListNavRefresh.vue, src/components/admin/table-list/table-list-table/TableListTable.scss, src/components/admin/table-list/table-list-tabs/TableListTabs.scss, src/components/admin/titlebar/Titlebar.scss, src/components/ui/button/Button.scss, src/components/ui/card/Card.scss, src/components/ui/dropdown/Dropdown.scss, src/components/ui/dropdown/Dropdown.vue, src/components/ui/form-autocomplete/FormAutocomplete.scss, src/components/ui/icon-button/IconButton.scss, src/scss/plugins/choices.scss, src/scss/tokens/tokens.scss
- Ajuste dos tokens semânticos.
=> [Fix] Ajuste dos tokens

src/components/ui/card/Card.scss
=> [Fix] Remover padding-bottom

src/components/ui/alert/Alert.scss, src/components/ui/dialog/Dialog.scss, src/scss/tokens/semantic/colors.scss
[Fix] Correções no tokens
- Ajustar overlay do componente dialog
- Remover dark-mode do ui-alert
- Adicionar token da marca rede orange
- Corrigir opacidade do token de background-overlay
=> fix: Correção nos tokens

src/components/admin/table-list/TableList.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11739)
- Atualiza table data quando muda o query param
=> Fix: Busca rápida não funciona na tela de pedido/produto

src/components/admin/media-card/MediaCard.scss, src/components/admin/sidebar/Sidebar.scss, src/components/admin/table-list/table-list-table/TableListTable.scss, src/components/admin/user-profile-card/UserProfileCard.scss, src/components/ui/alert/Alert.scss, src/components/ui/aside/Aside.scss, src/components/ui/dropdown/Dropdown.scss, src/components/ui/dropdown/Dropdown.stories.ts, src/components/ui/form-autocomplete/FormAutocomplete.scss, src/components/ui/form-colorpicker/FormColorPicker.scss, src/components/ui/form-select/FormSelect.scss, src/components/ui/form-tags/FormTags.scss, src/components/ui/form-wrapper/FormWrapper.scss, src/components/ui/tag/Tag.scss, src/scss/forms.scss, src/scss/mixins.scss, src/scss/tokens/semantic/colors.scss
[Fix] Correções gerais nos tokens
- Correções nos tokens das marcas Tray e Rede
- Correções gerais nos componentes
=> fix: Correções gerais nos tokens

src/components/admin/browser-select/BrowserSelectModal.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11756)
- corrigido espaçamento interno do form na modal de browser select
=> [task] ajustar o form-wrapper

src/scss/forms.scss, src/scss/mixins.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11790)
- corrigido cor de fundo do form-wrapper quando select
=> [fix] itens no list da busca rápida com cor errada

src/components/admin/table-list/table-list-nav/TableListNavCustomFilter.vue, src/components/admin/table-list/table-list-nav/TableListNavSortable.vue, src/components/ui/dropdown/Dropdown.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11795)
- corrigido exibição do dropdown no mobile com variante `right`
=> [fix] cortando menu dropdown no mobile

src/components/admin/savebar/Savebar.scss, src/components/ui/timeline/Timeline.scss
[Fix] Ajustes componentes timeline e savebar
- Correção de espaçamentos no componente de timeline
- Adição do token de sombra na savebar
=> [Fix] Ajustes componentes timeline e savebar

src/components/ui/button/Button.scss, src/components/ui/button/Button.vue
- Adição de classe combinada com os tamanhos do botão quando o mesmo só receber ícone.
=> [Task] Botão com variação de somente ícone

src/scss/mixins.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11841)
- corrigido cor do texto dos forms
=> [fix] quebra de layout no onboarding

src/components/admin/media-card/MediaCard.scss, src/components/admin/table-list/TableList.vue, src/components/admin/table-list/table-list-nav-filter/TableListNavFilter.vue, src/components/admin/table-list/table-list-nav/TableListNav.scss, src/components/admin/table-list/table-list-nav/TableListNavSortable.vue
- Adição da validação de navegação mobile para substituição da label por ícones na navbar da TableList,
- another change
=> [Fix] Responsividade da navbar na Table List

src/components/admin/table-list/TableList.vue, src/components/admin/table-list/table-list-nav-bulk/TableListNavBulk.vue, src/components/admin/table-list/table-list-nav-filter/TableListNavFilter.vue, src/components/admin/table-list/table-list-nav/TableListNav.scss, src/components/admin/table-list/table-list-nav/TableListNavCustomFilter.vue, src/components/ui/button/Button.scss
=> [Fix] Correções na table-list

src/components/admin/seo/Seo.scss
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11860)
- corrigido quebra de texto na interna dos produtos
=> [fix] quebra de texto na aba geral de produtos no mobile

src/components/admin/table-list/snippets/TableListEmptySearch.vue, src/components/admin/table-list/table-list-tags/TableListTags.vue, src/components/admin/table/Table.scss, src/components/ui/aside/Aside.scss, src/components/ui/form-wrapper/FormWrapper.scss, src/components/ui/toast/index.ts, src/scss/mixins.scss, src/scss/table.scss
[Fix] Correcoes dark mode e tokens antigos
- Correções gerais nos tokens
=> [Fix] Correcoes dark mode e tokens antigos

src/components/ui/dropdown/Dropdown.scss, src/components/ui/dropdown/DropdownItemButton.vue
- Adição do min-width da listagem do dropdown apenas para mobile.
- Adição do text-overflow ellipsis para os itens do dropdown quando passarem do min-width.
=> [Fix] Cortando texto no dropdown

src/components/ui/button/Button.scss, src/components/ui/form-wrapper/FormWrapper.scss, src/scss/helpers.scss
[fix link](xxxxxxx)
- corrigido token de cor do botão em formato de link
- corrigido tokens de input para webkit
=> [fix] ajustar tokens

src/components/ui/dropdown/Dropdown.scss, src/components/ui/icon-button/IconButton.vue
[Fix] Correção no ícone de dropdown
=> fix: Correções do ícone em dropdown

src/components/admin/quick-search/QuickSearch.vue, src/components/admin/sidebar/Sidebar.vue, src/helpers/index.ts, src/services/MobileDetector.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11949)
- Melhora validacao mobile
=> [Fix] Card de perfil esta aparecendo durante a rolagem em mobile

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11949)
- Validacao pelo css
=> [Fix] Card de perfil esta aparecendo durante a rolagem em mobile pelo css

src/components/admin/page-message-support/PageMessageSupport.scss, src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.vue, src/components/admin/table-list/table-list-nav-pagination/TableListNavPagination.scss, src/components/admin/titlebar/Titlebar.scss, src/components/admin/titlebar/Titlebar.vue, src/components/ui/aside/Aside.scss, src/components/ui/aside/Aside.vue, src/components/ui/button/Button.scss, src/components/ui/dropdown/Dropdown.scss, src/components/ui/form-wrapper/FormWrapper.scss, src/scss/tokens/tokens.scss
[Fix] Refinamentos nos componentes do DS
- Ajustar aside
- Sombra dropdown
- Botão de link
=> fix: Refinamentos nos componentes do DS

src/components/ui/form-currency/FormCurrency.vue, src/components/ui/form-textfield/FormTextFieldProps.ts, src/components/ui/form-textfield/FormTextfield.vue
- Adição do v-bind de todos atributos que o FormWrapper recebe para o input possibilitando assim mais opções de regra da máscara, por exemplo.
- Troca da interface para arquivo em separado.
- Correção do update do FormCurrency.
=> [Fix] Comportamento incorreto dos campos de dimensão do produto

src/components/ui/color-thumb/ColorThumb.scss, src/components/ui/color-thumb/ColorThumb.vue
[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/12011)
- corrigido exibição da imagem no color button
- corrigido estilização
=> [fix] imagem usada na cor não aparece na listagem

src/components/admin/media-card/MediaCard.scss, src/components/admin/media-card/MediaCard.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11778/)
- Adiciona prop `horizontal` para definir forma de exibicao do coimponente `MediaCard`
=> [Task] Adiciona props em media card

src/components/admin/titlebar/Titlebar.scss, src/components/admin/titlebar/Titlebar.vue, src/components/ui/link/Link.scss, src/components/ui/link/Link.vue
- Adição da prop de wrap no componente `Link`
- Correcão do tamanho dos botões da `TitleBar` em mobile.
=> [Hotfix] Ajustes visuais

src/components/admin/sidebar/Sidebar.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=12152)
- Inclusão do operador opcional nas chamadas do toggle de menu
=> [Hotfix] Sidebar menu toggle handle

src/components/admin/page-helper/PageHelper.vue
- Adição do window.open no click de todo component para abrir o link passado por prop em nova aba .
=> [Fix] Adição do window.open caso tenha helperlink

src/components/admin/page-helper/PageHelper.vue, src/components/admin/sidebar/Sidebar.vue, src/components/admin/titlebar/Titlebar.scss, src/components/admin/titlebar/Titlebar.vue, src/components/ui/link/Link.scss, src/components/ui/link/Link.vue
- Adição do window.open no click de todo component para abrir o link passado por prop em nova aba.
- Inclusão do operador opcional nas chamadas do toggle de menu
- Correção geral de layout e tokens.
=> [Release] 3.0.2

src/components/admin/sidebar/Sidebar.vue, src/components/admin/sidebar/types.ts, src/components/ui/dropdown/Dropdown.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=12223)
- Inclusão dos params nos itens do Sidebar menu
- Troca para translateY no showOnTop do Dropdown para ser aplicado em menu com outros tamanhos.
=> [Hotfix] Params na rota e posição do Dropdown

src/components/admin/media-card/MediaCard.scss, src/components/admin/media-card/MediaCard.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%203?workitem=12287)
- Correcao bordar
- Modanca target blank
=> [Fix] Configuracoes media card

src/components/admin/home-bar/HomeBar.scss, src/components/admin/home-bar/HomeBar.stories.ts, src/components/admin/home-bar/HomeBar.vue, src/components/admin/sidebar/types.ts, src/components/ui/card-info-link/CardInfoLink.scss, src/components/ui/card-info-link/CardInfoLink.stories.ts, src/components/ui/card-info-link/CardInfoLink.vue, src/index.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=12623)
Inclusão dos componentes que estavam no admin-platform, e sera usado nos outros módulos
- Inclusão do componente CardInfoLink
- Inclusão do componentes HomeBar
=> [Task] Criar a home do marketplace

src/components/admin/media-card/MediaCard.scss, src/components/admin/media-card/MediaCard.vue, src/types/IAction.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%203?workitem=12720
- Adiciona tamanho nos btns do media card
- Ajusta radius do card
- Organiza codigo
=> [Task] Melhorias no MediaCard

src/components/ui/modal/Modal.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=12944)
- Inclusão do slot caption no componente de Modal para satisfazer as necessidades do modal de instalação de app no marketplace
=> [Task] Criar tratamento de erro na instalação do App

src/components/admin/layout/Layout.scss, src/components/admin/page/Page.scss, src/components/ui/skeleton/Skeleton.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%204?workitem=13072)
- Modifica width para 100% no componente layout em mobile
- Remove padding não necessário
- ajusta border do skeleton
=> [Task] Layout mobile 

src/components/admin/platform-select/PlatformSelect.scss, src/components/admin/platform-select/PlatformSelect.vue, src/components/ui/card-info-link/CardInfoLink.scss, src/components/ui/icon/Icon.vue, src/components/ui/select-item-card/SelectItemCard.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=13173)
- Ajustes visuais dos componentes usados no Marketplace
=> [Fix] Ajustes visuais

src/components/admin/browser-select/BrowserSelect.vue
- Adição da validação da existência do array populado para o disparo do watch.
=> [Fix] Correção do carregamento dos produtos selecionados no BrowserSelect

src/components/admin/platform-select/PlatformSelect.scss, src/components/admin/platform-select/PlatformSelect.stories.ts, src/components/admin/sidebar-header/SidebarHeader.stories.ts, src/components/admin/sidebar-header/SidebarHeader.vue, src/components/admin/sidebar/Sidebar.scss
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/13251)
- Ajustes de css para o Seletor de Plataforma
- Criação do componente de header da sidebar para ser compartilhado entre os painéis.
=> [Task] Criar Logo no header do menu

src/components/admin/platform-select/PlatformSelect.scss, src/components/admin/platform-select/PlatformSelect.stories.ts, src/components/admin/platform-select/PlatformSelect.vue, src/components/admin/platform-select/PlatformSelectTypes.ts, src/components/admin/sidebar/Sidebar.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=13283)
- Inclusão de badges de Beta e Em Breve no componente de PlatformSelect
=> [Task] Criar badges nas tabs Beta e Em Breve

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue, src/components/admin/sidebar/types.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=13340)
- Inclusão de Badge como IncomingSoon para menu na SideBar
=> [Task] Bloquear Amazon no marketplace - Em Breve

src/components/admin/media-card/MediaCard.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%205?workitem=13309)
- Adiciona diretiva v-html no media card
=> [task] Adiciona diretiva v-html no media card

src/components/ui/image/Image.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%205?workitem=13266)
- Adiciona tokens corretos nas bordas do image componente
=> [Fix] Corrige bordas do componente Image

src/components/admin/browser-select/BrowserSelect.vue, src/components/admin/layout/Layout.scss, src/components/admin/media-card/MediaCard.vue, src/components/admin/page/Page.scss, src/components/ui/form-validation/FormValidation.vue, src/components/ui/image/Image.scss, src/components/ui/skeleton/Skeleton.scss
- Modifica `width` para 100% no componente `Layout` em mobile
- Remove `padding` não necessário do componente `Page`
- Ajusta `border` do componente `Skeleton`
- Modifica description do componente `MediaCard` de `v-text` por `v-html`
- Modifica validação do `BrowserSelect` para disparar o `watch`.
=> [Release] 3.0.5

src/components/admin/panel-skeleton/PanelSkeleton.scss, src/components/admin/panel-skeleton/PanelSkeleton.stories.ts, src/components/admin/panel-skeleton/PanelSkeleton.vue, src/components/admin/sidebar-header/SidebarHeader.vue, src/index.ts
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=13344)
- Componente de Skeleton para o painel criado.
=> [Task] Adicionar Loader inicial nos paineis

src/components/admin/panel-skeleton/PanelSkeleton.scss
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=13344)
- Inclusão do max-width no content do PanelSkeleton
=> [Fix] inclusao do max-width no content do skeleton

src/components/admin/media-card/MediaCard.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%205?workitem=13587)
- Adiciona acao de click nos botoes do media card
=> [Task] Adiciona acao de click nos botoes do media card

src/components/admin/sidebar/Sidebar.scss, src/components/admin/sidebar/Sidebar.vue
[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=13541)
- Ajuste do tamanho da badge de Em breve
=> [Fix] Ajustar tamanho da badge de "Em breve"

src/components/ui/form-colorpicker/FormColorpicker.vue
- Adição da classe customizada para adicionar o z-index.
=> [Fix] Corrigir z-index do color picker

src/components/admin/titlebar/Titlebar.scss, src/scss/tokens/semantic/typographies.scss
[Fix] Corrigir token de line-height
- Remover line-height fixo da titlebar
- Ajustar line-height do token de tipografia
=> [Fix] Corrigir token de line height

src/components/admin/user-profile-card/UserProfileCard.vue
- Adiciona target blank quando existir href nas opcoes do dropdown
=> [Task] Adiciona target blank no Profile Card

src/components/ui/form-radio/FormRadio.scss
[Fix] Remoção de borda do radio-button
- Remoção da borda do radio-button quando possui mais de um radio-button na sequência.
=> [Fix] Remoção de borda do radio-button

src/components/admin/sidebar/Sidebar.vue, src/components/admin/sidebar/types.ts
- Adição da prop opcional `highlatedLabel` no componente `Sidebar`.
=> Release 3.1.5

src/components/admin/savebar/Savebar.vue
- Adição da prop disabled no botão de save da `SaveBar`.
=> [Hotfix] Adição do disabled na SaveBar

src/components/admin/browser-select/BrowserSelect.vue
- Adição da prop `paginateListLimit ` para limit de itens a serem exibidos na lista de itens selecionados do `BrowserSelect`.
- Adição da busca seccionada com base na `paginateListLimit `.
=> [Feature] Adição da paginação dos itens na lista do BrowserSelect

src/components/admin/browser-select/BrowserSelect.vue, src/components/admin/table-list/TableList.vue, src/components/admin/titlebar/Titlebar.vue, src/types/ITableListConfig.ts
- Adição da prop `paginateListLimit ` para limit de itens a serem exibidos na lista de itens selecionados do `BrowserSelect`.
- Adição da busca seccionada com base na `paginateListLimit `.
- Adição da prop `hideTabsFilter`e `hideButtonFilter` para possibilitar ocultar Tabs de filtro nativas e botão de filtro respectivamente na `TableList`.
- Adição da prop `variantBtn` no `TitleBar` para controle da variação do botão no componente.
=> [Release] 3.1.7

src/components/admin/browser-select/BrowserSelect.vue
- Adição da busca de produtos da lista do `BrowserSelect` por lotes de ids.
=> [Hotfix] Correção na busca de produtos da lista do BrowserSelect

package.json, src/components/admin/apexchart/Apexchart.vue
Corrige o versionamento do DS para ficar de acordo com as versões / tags lançadas e modifica a importação da biblioteca Apexcharts para garantir o uso dos arquivos prontos ao invés de usar o source.
=> Corrige package.json DS e importação da biblioteca apexcharts

src/components/ui/tag/Tag.vue
- [Fix] Modificação da obrigatoriedade de prop no componente `Tag`.
=> [Fix] Correção da obrigatoriedade de prop

src/components/admin/browser-select/BrowserSelect.vue, src/components/admin/titlebar/Titlebar.scss
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/18804)
- Ajusta CSS do tamanho do secondary button;
- Ajusta seleção do browserSelect quando 0 aplicados;
https://github.com/user-attachments/assets/19271483-9106-433c-bd33-aae9d5286fc3
=> [Fix] Correções no DS

src/components/admin/browser-select/BrowserSelect.vue
[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/18836)
- Correção na lógica do watch para limpar ids selecionados quando todos forem removidos pelo pai.
=> [Fix] BrowserSelectModal com item ativo

src/components/admin/table-list/TableList.vue, src/components/admin/table-list/table-list-nav/TableListNavRefresh.vue
- Adição do parâmetro de timestamp na requisição feita pelo refresh button da `TableList`.
=> [Hotfix] Adição de timestamp no fetch da TableList

src/components/admin/browser-select/BrowserSelect.vue, src/components/admin/table-list/TableList.vue, src/components/admin/table-list/table-list-nav/TableListNavRefresh.vue, src/components/admin/titlebar/Titlebar.scss
- Adição do parâmetro de timestamp na requisição feita pelo refresh button da `TableList`;
- Correção do tamanho do secondary button no `Titlebar.scss`;
- Correção da seleção do browserSelect quando 0 aplicados;
https://github.com/user-attachments/assets/19271483-9106-433c-bd33-aae9d5286fc3
=> [Release] 3.1.11
